services:
# mariadb section
  mariadb:
    build:
      context: .
      dockerfile: requirements/mariadb/Dockerfile
    container_name: mariadb
    networks:
      - inception
    env_file:
      - .env
    restart: always
    volumes:
      - mariadb_data:/var/lib/mysql
# nginx section
  nginx:
    build: 
      context: .
      dockerfile: requirements/nginx/Dockerfile
    container_name: nginx
    networks:
      - inception
    depends_on:
      - wordpress
    env_file:
      - .env
    ports:
      - "443:443"
    volumes:
      - wordpress_files:/var/www/html
    restart: on-failure
# wordpress section
  wordpress:
    build: 
      context: .
      dockerfile: requirements/wordpress/Dockerfile
    container_name: wordpress
    env_file:
      - .env
    networks:
      - inception
    depends_on:
      - mariadb
    restart: always
    volumes:
      - wordpress_files:/var/www/html
# network section
networks:
    inception:
        driver: bridge
# volumes section
volumes:
  mariadb_data: 
    driver: local
    driver_opts:
      type: none
      device: /home/omakran/data/mariadb
      o: bind

  wordpress_files:
    driver: local
    driver_opts:
      type: none
      device: /home/omakran/data/wordpress
      o: bind